### ISSUE TITLE
MVP release

### ISSUE THREAD

**Issue by awitherow** [awitherow/moonbot#1]
# todo

- [x] sketch out bare bones "functioning" psuedocode
- [x] ensure that it is actually working
- [x] ensure data storage to file system
- [x] package and run on raspberry pi at home.

**Comment by awitherow** [comment]
Currently having trouble with storing data for the coins... stacktrace

```bash
python ./src/main.py
Starting moon_call.
Calling twitter for $LTC
Scoring $LTCtweet quality
Traceback (most recent call last):
  File "./src/main.py", line 75, in <module>
    moon_call()
  File "./src/main.py", line 39, in moon_call
    db.add(path="symbols", file_name=coin_symbol, entry=entry)
  File "/Users/austinwitherow/dev/moonbot/src/db.py", line 20, in add
    database.insert(entry)
  File "/Library/Python/2.7/site-packages/tinydb/database.py", line 338, in insert
    self._write(data)
  File "/Library/Python/2.7/site-packages/tinydb/database.py", line 294, in _write
    self._storage.write(values)
  File "/Library/Python/2.7/site-packages/tinydb/database.py", line 46, in write
    self._storage.write(data)
  File "/Library/Python/2.7/site-packages/tinydb/storages.py", line 109, in write
    serialized = json.dumps(data, **self.kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 8, 9, 0, 6, 49, 161118) is not JSON serializable
make: *** [run] Error 1
```

**Comment by awitherow** [comment]
I have solved this! MVP is up and running at https://t.me/joinchat/AAAAAEKhK3X1ngRfVa_NWA
